/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-02-13 at 00:12:37 UTC 
 * Modify at your own risk.
 */

package com.demomapas.model.detenidoendpoint;

/**
 * Service definition for Detenidoendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link DetenidoendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Detenidoendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the detenidoendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://civic-athlete-851.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "detenidoendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Detenidoendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Detenidoendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getDetenido".
   *
   * This request holds the parameters needed by the detenidoendpoint server.  After setting any
   * optional parameters, call the {@link GetDetenido#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetDetenido getDetenido(java.lang.Long id) throws java.io.IOException {
    GetDetenido result = new GetDetenido(id);
    initialize(result);
    return result;
  }

  public class GetDetenido extends DetenidoendpointRequest<com.demomapas.model.detenidoendpoint.model.Detenido> {

    private static final String REST_PATH = "detenido/{id}";

    /**
     * Create a request for the method "getDetenido".
     *
     * This request holds the parameters needed by the the detenidoendpoint server.  After setting any
     * optional parameters, call the {@link GetDetenido#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetDetenido#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetDetenido(java.lang.Long id) {
      super(Detenidoendpoint.this, "GET", REST_PATH, null, com.demomapas.model.detenidoendpoint.model.Detenido.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetDetenido setAlt(java.lang.String alt) {
      return (GetDetenido) super.setAlt(alt);
    }

    @Override
    public GetDetenido setFields(java.lang.String fields) {
      return (GetDetenido) super.setFields(fields);
    }

    @Override
    public GetDetenido setKey(java.lang.String key) {
      return (GetDetenido) super.setKey(key);
    }

    @Override
    public GetDetenido setOauthToken(java.lang.String oauthToken) {
      return (GetDetenido) super.setOauthToken(oauthToken);
    }

    @Override
    public GetDetenido setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetDetenido) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetDetenido setQuotaUser(java.lang.String quotaUser) {
      return (GetDetenido) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetDetenido setUserIp(java.lang.String userIp) {
      return (GetDetenido) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetDetenido setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetDetenido set(String parameterName, Object value) {
      return (GetDetenido) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertDetenido".
   *
   * This request holds the parameters needed by the detenidoendpoint server.  After setting any
   * optional parameters, call the {@link InsertDetenido#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.demomapas.model.detenidoendpoint.model.Detenido}
   * @return the request
   */
  public InsertDetenido insertDetenido(com.demomapas.model.detenidoendpoint.model.Detenido content) throws java.io.IOException {
    InsertDetenido result = new InsertDetenido(content);
    initialize(result);
    return result;
  }

  public class InsertDetenido extends DetenidoendpointRequest<com.demomapas.model.detenidoendpoint.model.Detenido> {

    private static final String REST_PATH = "detenido";

    /**
     * Create a request for the method "insertDetenido".
     *
     * This request holds the parameters needed by the the detenidoendpoint server.  After setting any
     * optional parameters, call the {@link InsertDetenido#execute()} method to invoke the remote
     * operation. <p> {@link InsertDetenido#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.demomapas.model.detenidoendpoint.model.Detenido}
     * @since 1.13
     */
    protected InsertDetenido(com.demomapas.model.detenidoendpoint.model.Detenido content) {
      super(Detenidoendpoint.this, "POST", REST_PATH, content, com.demomapas.model.detenidoendpoint.model.Detenido.class);
    }

    @Override
    public InsertDetenido setAlt(java.lang.String alt) {
      return (InsertDetenido) super.setAlt(alt);
    }

    @Override
    public InsertDetenido setFields(java.lang.String fields) {
      return (InsertDetenido) super.setFields(fields);
    }

    @Override
    public InsertDetenido setKey(java.lang.String key) {
      return (InsertDetenido) super.setKey(key);
    }

    @Override
    public InsertDetenido setOauthToken(java.lang.String oauthToken) {
      return (InsertDetenido) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertDetenido setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertDetenido) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertDetenido setQuotaUser(java.lang.String quotaUser) {
      return (InsertDetenido) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertDetenido setUserIp(java.lang.String userIp) {
      return (InsertDetenido) super.setUserIp(userIp);
    }

    @Override
    public InsertDetenido set(String parameterName, Object value) {
      return (InsertDetenido) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listDetenido".
   *
   * This request holds the parameters needed by the detenidoendpoint server.  After setting any
   * optional parameters, call the {@link ListDetenido#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListDetenido listDetenido() throws java.io.IOException {
    ListDetenido result = new ListDetenido();
    initialize(result);
    return result;
  }

  public class ListDetenido extends DetenidoendpointRequest<com.demomapas.model.detenidoendpoint.model.CollectionResponseDetenido> {

    private static final String REST_PATH = "detenido";

    /**
     * Create a request for the method "listDetenido".
     *
     * This request holds the parameters needed by the the detenidoendpoint server.  After setting any
     * optional parameters, call the {@link ListDetenido#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListDetenido#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListDetenido() {
      super(Detenidoendpoint.this, "GET", REST_PATH, null, com.demomapas.model.detenidoendpoint.model.CollectionResponseDetenido.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListDetenido setAlt(java.lang.String alt) {
      return (ListDetenido) super.setAlt(alt);
    }

    @Override
    public ListDetenido setFields(java.lang.String fields) {
      return (ListDetenido) super.setFields(fields);
    }

    @Override
    public ListDetenido setKey(java.lang.String key) {
      return (ListDetenido) super.setKey(key);
    }

    @Override
    public ListDetenido setOauthToken(java.lang.String oauthToken) {
      return (ListDetenido) super.setOauthToken(oauthToken);
    }

    @Override
    public ListDetenido setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListDetenido) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListDetenido setQuotaUser(java.lang.String quotaUser) {
      return (ListDetenido) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListDetenido setUserIp(java.lang.String userIp) {
      return (ListDetenido) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListDetenido setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListDetenido setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListDetenido set(String parameterName, Object value) {
      return (ListDetenido) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeDetenido".
   *
   * This request holds the parameters needed by the detenidoendpoint server.  After setting any
   * optional parameters, call the {@link RemoveDetenido#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveDetenido removeDetenido(java.lang.Long id) throws java.io.IOException {
    RemoveDetenido result = new RemoveDetenido(id);
    initialize(result);
    return result;
  }

  public class RemoveDetenido extends DetenidoendpointRequest<Void> {

    private static final String REST_PATH = "detenido/{id}";

    /**
     * Create a request for the method "removeDetenido".
     *
     * This request holds the parameters needed by the the detenidoendpoint server.  After setting any
     * optional parameters, call the {@link RemoveDetenido#execute()} method to invoke the remote
     * operation. <p> {@link RemoveDetenido#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveDetenido(java.lang.Long id) {
      super(Detenidoendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveDetenido setAlt(java.lang.String alt) {
      return (RemoveDetenido) super.setAlt(alt);
    }

    @Override
    public RemoveDetenido setFields(java.lang.String fields) {
      return (RemoveDetenido) super.setFields(fields);
    }

    @Override
    public RemoveDetenido setKey(java.lang.String key) {
      return (RemoveDetenido) super.setKey(key);
    }

    @Override
    public RemoveDetenido setOauthToken(java.lang.String oauthToken) {
      return (RemoveDetenido) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveDetenido setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveDetenido) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveDetenido setQuotaUser(java.lang.String quotaUser) {
      return (RemoveDetenido) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveDetenido setUserIp(java.lang.String userIp) {
      return (RemoveDetenido) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveDetenido setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveDetenido set(String parameterName, Object value) {
      return (RemoveDetenido) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateDetenido".
   *
   * This request holds the parameters needed by the detenidoendpoint server.  After setting any
   * optional parameters, call the {@link UpdateDetenido#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.demomapas.model.detenidoendpoint.model.Detenido}
   * @return the request
   */
  public UpdateDetenido updateDetenido(com.demomapas.model.detenidoendpoint.model.Detenido content) throws java.io.IOException {
    UpdateDetenido result = new UpdateDetenido(content);
    initialize(result);
    return result;
  }

  public class UpdateDetenido extends DetenidoendpointRequest<com.demomapas.model.detenidoendpoint.model.Detenido> {

    private static final String REST_PATH = "detenido";

    /**
     * Create a request for the method "updateDetenido".
     *
     * This request holds the parameters needed by the the detenidoendpoint server.  After setting any
     * optional parameters, call the {@link UpdateDetenido#execute()} method to invoke the remote
     * operation. <p> {@link UpdateDetenido#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.demomapas.model.detenidoendpoint.model.Detenido}
     * @since 1.13
     */
    protected UpdateDetenido(com.demomapas.model.detenidoendpoint.model.Detenido content) {
      super(Detenidoendpoint.this, "PUT", REST_PATH, content, com.demomapas.model.detenidoendpoint.model.Detenido.class);
    }

    @Override
    public UpdateDetenido setAlt(java.lang.String alt) {
      return (UpdateDetenido) super.setAlt(alt);
    }

    @Override
    public UpdateDetenido setFields(java.lang.String fields) {
      return (UpdateDetenido) super.setFields(fields);
    }

    @Override
    public UpdateDetenido setKey(java.lang.String key) {
      return (UpdateDetenido) super.setKey(key);
    }

    @Override
    public UpdateDetenido setOauthToken(java.lang.String oauthToken) {
      return (UpdateDetenido) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateDetenido setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateDetenido) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateDetenido setQuotaUser(java.lang.String quotaUser) {
      return (UpdateDetenido) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateDetenido setUserIp(java.lang.String userIp) {
      return (UpdateDetenido) super.setUserIp(userIp);
    }

    @Override
    public UpdateDetenido set(String parameterName, Object value) {
      return (UpdateDetenido) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Detenidoendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Detenidoendpoint}. */
    @Override
    public Detenidoendpoint build() {
      return new Detenidoendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link DetenidoendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setDetenidoendpointRequestInitializer(
        DetenidoendpointRequestInitializer detenidoendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(detenidoendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
