/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-03-31 at 04:56:13 UTC 
 * Modify at your own risk.
 */

package com.virtualef.pgj.service.requireService;

/**
 * Service definition for RequireService (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link RequireServiceRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class RequireService extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the requireService library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://civic-athlete-851.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "requireService/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public RequireService(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  RequireService(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getRequire".
   *
   * This request holds the parameters needed by the requireService server.  After setting any
   * optional parameters, call the {@link GetRequire#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetRequire getRequire(java.lang.Long id) throws java.io.IOException {
    GetRequire result = new GetRequire(id);
    initialize(result);
    return result;
  }

  public class GetRequire extends RequireServiceRequest<com.virtualef.pgj.service.requireService.model.RequireDto> {

    private static final String REST_PATH = "requiredto/{id}";

    /**
     * Create a request for the method "getRequire".
     *
     * This request holds the parameters needed by the the requireService server.  After setting any
     * optional parameters, call the {@link GetRequire#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetRequire#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetRequire(java.lang.Long id) {
      super(RequireService.this, "GET", REST_PATH, null, com.virtualef.pgj.service.requireService.model.RequireDto.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetRequire setAlt(java.lang.String alt) {
      return (GetRequire) super.setAlt(alt);
    }

    @Override
    public GetRequire setFields(java.lang.String fields) {
      return (GetRequire) super.setFields(fields);
    }

    @Override
    public GetRequire setKey(java.lang.String key) {
      return (GetRequire) super.setKey(key);
    }

    @Override
    public GetRequire setOauthToken(java.lang.String oauthToken) {
      return (GetRequire) super.setOauthToken(oauthToken);
    }

    @Override
    public GetRequire setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetRequire) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetRequire setQuotaUser(java.lang.String quotaUser) {
      return (GetRequire) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetRequire setUserIp(java.lang.String userIp) {
      return (GetRequire) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetRequire setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetRequire set(String parameterName, Object value) {
      return (GetRequire) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getRequires".
   *
   * This request holds the parameters needed by the requireService server.  After setting any
   * optional parameters, call the {@link GetRequires#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public GetRequires getRequires() throws java.io.IOException {
    GetRequires result = new GetRequires();
    initialize(result);
    return result;
  }

  public class GetRequires extends RequireServiceRequest<com.virtualef.pgj.service.requireService.model.CollectionResponseRequireDto> {

    private static final String REST_PATH = "requiredto";

    /**
     * Create a request for the method "getRequires".
     *
     * This request holds the parameters needed by the the requireService server.  After setting any
     * optional parameters, call the {@link GetRequires#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetRequires#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected GetRequires() {
      super(RequireService.this, "GET", REST_PATH, null, com.virtualef.pgj.service.requireService.model.CollectionResponseRequireDto.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetRequires setAlt(java.lang.String alt) {
      return (GetRequires) super.setAlt(alt);
    }

    @Override
    public GetRequires setFields(java.lang.String fields) {
      return (GetRequires) super.setFields(fields);
    }

    @Override
    public GetRequires setKey(java.lang.String key) {
      return (GetRequires) super.setKey(key);
    }

    @Override
    public GetRequires setOauthToken(java.lang.String oauthToken) {
      return (GetRequires) super.setOauthToken(oauthToken);
    }

    @Override
    public GetRequires setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetRequires) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetRequires setQuotaUser(java.lang.String quotaUser) {
      return (GetRequires) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetRequires setUserIp(java.lang.String userIp) {
      return (GetRequires) super.setUserIp(userIp);
    }

    @Override
    public GetRequires set(String parameterName, Object value) {
      return (GetRequires) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertRequire".
   *
   * This request holds the parameters needed by the requireService server.  After setting any
   * optional parameters, call the {@link InsertRequire#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.virtualef.pgj.service.requireService.model.RequireDto}
   * @return the request
   */
  public InsertRequire insertRequire(com.virtualef.pgj.service.requireService.model.RequireDto content) throws java.io.IOException {
    InsertRequire result = new InsertRequire(content);
    initialize(result);
    return result;
  }

  public class InsertRequire extends RequireServiceRequest<com.virtualef.pgj.service.requireService.model.RequireDto> {

    private static final String REST_PATH = "requiredto";

    /**
     * Create a request for the method "insertRequire".
     *
     * This request holds the parameters needed by the the requireService server.  After setting any
     * optional parameters, call the {@link InsertRequire#execute()} method to invoke the remote
     * operation. <p> {@link InsertRequire#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.virtualef.pgj.service.requireService.model.RequireDto}
     * @since 1.13
     */
    protected InsertRequire(com.virtualef.pgj.service.requireService.model.RequireDto content) {
      super(RequireService.this, "POST", REST_PATH, content, com.virtualef.pgj.service.requireService.model.RequireDto.class);
    }

    @Override
    public InsertRequire setAlt(java.lang.String alt) {
      return (InsertRequire) super.setAlt(alt);
    }

    @Override
    public InsertRequire setFields(java.lang.String fields) {
      return (InsertRequire) super.setFields(fields);
    }

    @Override
    public InsertRequire setKey(java.lang.String key) {
      return (InsertRequire) super.setKey(key);
    }

    @Override
    public InsertRequire setOauthToken(java.lang.String oauthToken) {
      return (InsertRequire) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertRequire setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertRequire) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertRequire setQuotaUser(java.lang.String quotaUser) {
      return (InsertRequire) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertRequire setUserIp(java.lang.String userIp) {
      return (InsertRequire) super.setUserIp(userIp);
    }

    @Override
    public InsertRequire set(String parameterName, Object value) {
      return (InsertRequire) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeRequire".
   *
   * This request holds the parameters needed by the requireService server.  After setting any
   * optional parameters, call the {@link RemoveRequire#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveRequire removeRequire(java.lang.Long id) throws java.io.IOException {
    RemoveRequire result = new RemoveRequire(id);
    initialize(result);
    return result;
  }

  public class RemoveRequire extends RequireServiceRequest<Void> {

    private static final String REST_PATH = "requiredto/{id}";

    /**
     * Create a request for the method "removeRequire".
     *
     * This request holds the parameters needed by the the requireService server.  After setting any
     * optional parameters, call the {@link RemoveRequire#execute()} method to invoke the remote
     * operation. <p> {@link RemoveRequire#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveRequire(java.lang.Long id) {
      super(RequireService.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveRequire setAlt(java.lang.String alt) {
      return (RemoveRequire) super.setAlt(alt);
    }

    @Override
    public RemoveRequire setFields(java.lang.String fields) {
      return (RemoveRequire) super.setFields(fields);
    }

    @Override
    public RemoveRequire setKey(java.lang.String key) {
      return (RemoveRequire) super.setKey(key);
    }

    @Override
    public RemoveRequire setOauthToken(java.lang.String oauthToken) {
      return (RemoveRequire) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveRequire setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveRequire) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveRequire setQuotaUser(java.lang.String quotaUser) {
      return (RemoveRequire) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveRequire setUserIp(java.lang.String userIp) {
      return (RemoveRequire) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveRequire setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveRequire set(String parameterName, Object value) {
      return (RemoveRequire) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateRequire".
   *
   * This request holds the parameters needed by the requireService server.  After setting any
   * optional parameters, call the {@link UpdateRequire#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.virtualef.pgj.service.requireService.model.RequireDto}
   * @return the request
   */
  public UpdateRequire updateRequire(com.virtualef.pgj.service.requireService.model.RequireDto content) throws java.io.IOException {
    UpdateRequire result = new UpdateRequire(content);
    initialize(result);
    return result;
  }

  public class UpdateRequire extends RequireServiceRequest<com.virtualef.pgj.service.requireService.model.RequireDto> {

    private static final String REST_PATH = "requiredto";

    /**
     * Create a request for the method "updateRequire".
     *
     * This request holds the parameters needed by the the requireService server.  After setting any
     * optional parameters, call the {@link UpdateRequire#execute()} method to invoke the remote
     * operation. <p> {@link UpdateRequire#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.virtualef.pgj.service.requireService.model.RequireDto}
     * @since 1.13
     */
    protected UpdateRequire(com.virtualef.pgj.service.requireService.model.RequireDto content) {
      super(RequireService.this, "PUT", REST_PATH, content, com.virtualef.pgj.service.requireService.model.RequireDto.class);
    }

    @Override
    public UpdateRequire setAlt(java.lang.String alt) {
      return (UpdateRequire) super.setAlt(alt);
    }

    @Override
    public UpdateRequire setFields(java.lang.String fields) {
      return (UpdateRequire) super.setFields(fields);
    }

    @Override
    public UpdateRequire setKey(java.lang.String key) {
      return (UpdateRequire) super.setKey(key);
    }

    @Override
    public UpdateRequire setOauthToken(java.lang.String oauthToken) {
      return (UpdateRequire) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateRequire setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateRequire) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateRequire setQuotaUser(java.lang.String quotaUser) {
      return (UpdateRequire) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateRequire setUserIp(java.lang.String userIp) {
      return (UpdateRequire) super.setUserIp(userIp);
    }

    @Override
    public UpdateRequire set(String parameterName, Object value) {
      return (UpdateRequire) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link RequireService}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link RequireService}. */
    @Override
    public RequireService build() {
      return new RequireService(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link RequireServiceRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setRequireServiceRequestInitializer(
        RequireServiceRequestInitializer requireserviceRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(requireserviceRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
