/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-03-31 at 05:13:55 UTC 
 * Modify at your own risk.
 */

package com.virtualef.pgj.service.commandmentService.model;

/**
 * Model definition for CommandmentDto.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the commandmentService. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class CommandmentDto extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private AgentDto agent;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long area;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> audio;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String colony;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long commandmentType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String country;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long court;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long crime;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String date;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String department;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> evidence;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idAgent;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idRequire;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String inquest;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float latitude;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float longitude;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String number;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String observations;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long order;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long record;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private RequireDto require;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String state;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean status;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String street;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String town;

  /**
   * @return value or {@code null} for none
   */
  public AgentDto getAgent() {
    return agent;
  }

  /**
   * @param agent agent or {@code null} for none
   */
  public CommandmentDto setAgent(AgentDto agent) {
    this.agent = agent;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getArea() {
    return area;
  }

  /**
   * @param area area or {@code null} for none
   */
  public CommandmentDto setArea(java.lang.Long area) {
    this.area = area;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getAudio() {
    return audio;
  }

  /**
   * @param audio audio or {@code null} for none
   */
  public CommandmentDto setAudio(java.util.List<java.lang.String> audio) {
    this.audio = audio;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getColony() {
    return colony;
  }

  /**
   * @param colony colony or {@code null} for none
   */
  public CommandmentDto setColony(java.lang.String colony) {
    this.colony = colony;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCommandmentType() {
    return commandmentType;
  }

  /**
   * @param commandmentType commandmentType or {@code null} for none
   */
  public CommandmentDto setCommandmentType(java.lang.Long commandmentType) {
    this.commandmentType = commandmentType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCountry() {
    return country;
  }

  /**
   * @param country country or {@code null} for none
   */
  public CommandmentDto setCountry(java.lang.String country) {
    this.country = country;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCourt() {
    return court;
  }

  /**
   * @param court court or {@code null} for none
   */
  public CommandmentDto setCourt(java.lang.Long court) {
    this.court = court;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCrime() {
    return crime;
  }

  /**
   * @param crime crime or {@code null} for none
   */
  public CommandmentDto setCrime(java.lang.Long crime) {
    this.crime = crime;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDate() {
    return date;
  }

  /**
   * @param date date or {@code null} for none
   */
  public CommandmentDto setDate(java.lang.String date) {
    this.date = date;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDepartment() {
    return department;
  }

  /**
   * @param department department or {@code null} for none
   */
  public CommandmentDto setDepartment(java.lang.String department) {
    this.department = department;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getEvidence() {
    return evidence;
  }

  /**
   * @param evidence evidence or {@code null} for none
   */
  public CommandmentDto setEvidence(java.util.List<java.lang.String> evidence) {
    this.evidence = evidence;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public CommandmentDto setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdAgent() {
    return idAgent;
  }

  /**
   * @param idAgent idAgent or {@code null} for none
   */
  public CommandmentDto setIdAgent(java.lang.Long idAgent) {
    this.idAgent = idAgent;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdRequire() {
    return idRequire;
  }

  /**
   * @param idRequire idRequire or {@code null} for none
   */
  public CommandmentDto setIdRequire(java.lang.Long idRequire) {
    this.idRequire = idRequire;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getInquest() {
    return inquest;
  }

  /**
   * @param inquest inquest or {@code null} for none
   */
  public CommandmentDto setInquest(java.lang.String inquest) {
    this.inquest = inquest;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getLatitude() {
    return latitude;
  }

  /**
   * @param latitude latitude or {@code null} for none
   */
  public CommandmentDto setLatitude(java.lang.Float latitude) {
    this.latitude = latitude;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getLongitude() {
    return longitude;
  }

  /**
   * @param longitude longitude or {@code null} for none
   */
  public CommandmentDto setLongitude(java.lang.Float longitude) {
    this.longitude = longitude;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNumber() {
    return number;
  }

  /**
   * @param number number or {@code null} for none
   */
  public CommandmentDto setNumber(java.lang.String number) {
    this.number = number;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getObservations() {
    return observations;
  }

  /**
   * @param observations observations or {@code null} for none
   */
  public CommandmentDto setObservations(java.lang.String observations) {
    this.observations = observations;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getOrder() {
    return order;
  }

  /**
   * @param order order or {@code null} for none
   */
  public CommandmentDto setOrder(java.lang.Long order) {
    this.order = order;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getRecord() {
    return record;
  }

  /**
   * @param record record or {@code null} for none
   */
  public CommandmentDto setRecord(java.lang.Long record) {
    this.record = record;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public RequireDto getRequire() {
    return require;
  }

  /**
   * @param require require or {@code null} for none
   */
  public CommandmentDto setRequire(RequireDto require) {
    this.require = require;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getState() {
    return state;
  }

  /**
   * @param state state or {@code null} for none
   */
  public CommandmentDto setState(java.lang.String state) {
    this.state = state;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getStatus() {
    return status;
  }

  /**
   * @param status status or {@code null} for none
   */
  public CommandmentDto setStatus(java.lang.Boolean status) {
    this.status = status;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStreet() {
    return street;
  }

  /**
   * @param street street or {@code null} for none
   */
  public CommandmentDto setStreet(java.lang.String street) {
    this.street = street;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTown() {
    return town;
  }

  /**
   * @param town town or {@code null} for none
   */
  public CommandmentDto setTown(java.lang.String town) {
    this.town = town;
    return this;
  }

  @Override
  public CommandmentDto set(String fieldName, Object value) {
    return (CommandmentDto) super.set(fieldName, value);
  }

  @Override
  public CommandmentDto clone() {
    return (CommandmentDto) super.clone();
  }

}
