/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-02-16 at 20:23:08 UTC 
 * Modify at your own risk.
 */

package com.demomapas.model.tareaendpoint.model;

/**
 * Model definition for Tarea.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the tareaendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Tarea extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean estado;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fecha;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idAgente;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idDetenido;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idZona;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getEstado() {
    return estado;
  }

  /**
   * @param estado estado or {@code null} for none
   */
  public Tarea setEstado(java.lang.Boolean estado) {
    this.estado = estado;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFecha() {
    return fecha;
  }

  /**
   * @param fecha fecha or {@code null} for none
   */
  public Tarea setFecha(java.lang.String fecha) {
    this.fecha = fecha;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Tarea setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdAgente() {
    return idAgente;
  }

  /**
   * @param idAgente idAgente or {@code null} for none
   */
  public Tarea setIdAgente(java.lang.Long idAgente) {
    this.idAgente = idAgente;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdDetenido() {
    return idDetenido;
  }

  /**
   * @param idDetenido idDetenido or {@code null} for none
   */
  public Tarea setIdDetenido(java.lang.Long idDetenido) {
    this.idDetenido = idDetenido;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdZona() {
    return idZona;
  }

  /**
   * @param idZona idZona or {@code null} for none
   */
  public Tarea setIdZona(java.lang.Long idZona) {
    this.idZona = idZona;
    return this;
  }

  @Override
  public Tarea set(String fieldName, Object value) {
    return (Tarea) super.set(fieldName, value);
  }

  @Override
  public Tarea clone() {
    return (Tarea) super.clone();
  }

}
