/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-02-16 at 20:22:49 UTC 
 * Modify at your own risk.
 */

package com.demomapas.model.rutaendpoint;

/**
 * Service definition for Rutaendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link RutaendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Rutaendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the rutaendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://civic-athlete-851.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "rutaendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Rutaendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Rutaendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getRuta".
   *
   * This request holds the parameters needed by the rutaendpoint server.  After setting any optional
   * parameters, call the {@link GetRuta#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetRuta getRuta(java.lang.Long id) throws java.io.IOException {
    GetRuta result = new GetRuta(id);
    initialize(result);
    return result;
  }

  public class GetRuta extends RutaendpointRequest<com.demomapas.model.rutaendpoint.model.Ruta> {

    private static final String REST_PATH = "ruta/{id}";

    /**
     * Create a request for the method "getRuta".
     *
     * This request holds the parameters needed by the the rutaendpoint server.  After setting any
     * optional parameters, call the {@link GetRuta#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetRuta#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetRuta(java.lang.Long id) {
      super(Rutaendpoint.this, "GET", REST_PATH, null, com.demomapas.model.rutaendpoint.model.Ruta.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetRuta setAlt(java.lang.String alt) {
      return (GetRuta) super.setAlt(alt);
    }

    @Override
    public GetRuta setFields(java.lang.String fields) {
      return (GetRuta) super.setFields(fields);
    }

    @Override
    public GetRuta setKey(java.lang.String key) {
      return (GetRuta) super.setKey(key);
    }

    @Override
    public GetRuta setOauthToken(java.lang.String oauthToken) {
      return (GetRuta) super.setOauthToken(oauthToken);
    }

    @Override
    public GetRuta setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetRuta) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetRuta setQuotaUser(java.lang.String quotaUser) {
      return (GetRuta) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetRuta setUserIp(java.lang.String userIp) {
      return (GetRuta) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetRuta setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetRuta set(String parameterName, Object value) {
      return (GetRuta) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertRuta".
   *
   * This request holds the parameters needed by the rutaendpoint server.  After setting any optional
   * parameters, call the {@link InsertRuta#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.demomapas.model.rutaendpoint.model.Ruta}
   * @return the request
   */
  public InsertRuta insertRuta(com.demomapas.model.rutaendpoint.model.Ruta content) throws java.io.IOException {
    InsertRuta result = new InsertRuta(content);
    initialize(result);
    return result;
  }

  public class InsertRuta extends RutaendpointRequest<com.demomapas.model.rutaendpoint.model.Ruta> {

    private static final String REST_PATH = "ruta";

    /**
     * Create a request for the method "insertRuta".
     *
     * This request holds the parameters needed by the the rutaendpoint server.  After setting any
     * optional parameters, call the {@link InsertRuta#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertRuta#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.demomapas.model.rutaendpoint.model.Ruta}
     * @since 1.13
     */
    protected InsertRuta(com.demomapas.model.rutaendpoint.model.Ruta content) {
      super(Rutaendpoint.this, "POST", REST_PATH, content, com.demomapas.model.rutaendpoint.model.Ruta.class);
    }

    @Override
    public InsertRuta setAlt(java.lang.String alt) {
      return (InsertRuta) super.setAlt(alt);
    }

    @Override
    public InsertRuta setFields(java.lang.String fields) {
      return (InsertRuta) super.setFields(fields);
    }

    @Override
    public InsertRuta setKey(java.lang.String key) {
      return (InsertRuta) super.setKey(key);
    }

    @Override
    public InsertRuta setOauthToken(java.lang.String oauthToken) {
      return (InsertRuta) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertRuta setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertRuta) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertRuta setQuotaUser(java.lang.String quotaUser) {
      return (InsertRuta) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertRuta setUserIp(java.lang.String userIp) {
      return (InsertRuta) super.setUserIp(userIp);
    }

    @Override
    public InsertRuta set(String parameterName, Object value) {
      return (InsertRuta) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listRuta".
   *
   * This request holds the parameters needed by the rutaendpoint server.  After setting any optional
   * parameters, call the {@link ListRuta#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListRuta listRuta() throws java.io.IOException {
    ListRuta result = new ListRuta();
    initialize(result);
    return result;
  }

  public class ListRuta extends RutaendpointRequest<com.demomapas.model.rutaendpoint.model.CollectionResponseRuta> {

    private static final String REST_PATH = "ruta";

    /**
     * Create a request for the method "listRuta".
     *
     * This request holds the parameters needed by the the rutaendpoint server.  After setting any
     * optional parameters, call the {@link ListRuta#execute()} method to invoke the remote operation.
     * <p> {@link
     * ListRuta#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListRuta() {
      super(Rutaendpoint.this, "GET", REST_PATH, null, com.demomapas.model.rutaendpoint.model.CollectionResponseRuta.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListRuta setAlt(java.lang.String alt) {
      return (ListRuta) super.setAlt(alt);
    }

    @Override
    public ListRuta setFields(java.lang.String fields) {
      return (ListRuta) super.setFields(fields);
    }

    @Override
    public ListRuta setKey(java.lang.String key) {
      return (ListRuta) super.setKey(key);
    }

    @Override
    public ListRuta setOauthToken(java.lang.String oauthToken) {
      return (ListRuta) super.setOauthToken(oauthToken);
    }

    @Override
    public ListRuta setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListRuta) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListRuta setQuotaUser(java.lang.String quotaUser) {
      return (ListRuta) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListRuta setUserIp(java.lang.String userIp) {
      return (ListRuta) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListRuta setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListRuta setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListRuta set(String parameterName, Object value) {
      return (ListRuta) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeRuta".
   *
   * This request holds the parameters needed by the rutaendpoint server.  After setting any optional
   * parameters, call the {@link RemoveRuta#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveRuta removeRuta(java.lang.Long id) throws java.io.IOException {
    RemoveRuta result = new RemoveRuta(id);
    initialize(result);
    return result;
  }

  public class RemoveRuta extends RutaendpointRequest<Void> {

    private static final String REST_PATH = "ruta/{id}";

    /**
     * Create a request for the method "removeRuta".
     *
     * This request holds the parameters needed by the the rutaendpoint server.  After setting any
     * optional parameters, call the {@link RemoveRuta#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveRuta#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveRuta(java.lang.Long id) {
      super(Rutaendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveRuta setAlt(java.lang.String alt) {
      return (RemoveRuta) super.setAlt(alt);
    }

    @Override
    public RemoveRuta setFields(java.lang.String fields) {
      return (RemoveRuta) super.setFields(fields);
    }

    @Override
    public RemoveRuta setKey(java.lang.String key) {
      return (RemoveRuta) super.setKey(key);
    }

    @Override
    public RemoveRuta setOauthToken(java.lang.String oauthToken) {
      return (RemoveRuta) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveRuta setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveRuta) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveRuta setQuotaUser(java.lang.String quotaUser) {
      return (RemoveRuta) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveRuta setUserIp(java.lang.String userIp) {
      return (RemoveRuta) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveRuta setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveRuta set(String parameterName, Object value) {
      return (RemoveRuta) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateRuta".
   *
   * This request holds the parameters needed by the rutaendpoint server.  After setting any optional
   * parameters, call the {@link UpdateRuta#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.demomapas.model.rutaendpoint.model.Ruta}
   * @return the request
   */
  public UpdateRuta updateRuta(com.demomapas.model.rutaendpoint.model.Ruta content) throws java.io.IOException {
    UpdateRuta result = new UpdateRuta(content);
    initialize(result);
    return result;
  }

  public class UpdateRuta extends RutaendpointRequest<com.demomapas.model.rutaendpoint.model.Ruta> {

    private static final String REST_PATH = "ruta";

    /**
     * Create a request for the method "updateRuta".
     *
     * This request holds the parameters needed by the the rutaendpoint server.  After setting any
     * optional parameters, call the {@link UpdateRuta#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateRuta#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.demomapas.model.rutaendpoint.model.Ruta}
     * @since 1.13
     */
    protected UpdateRuta(com.demomapas.model.rutaendpoint.model.Ruta content) {
      super(Rutaendpoint.this, "PUT", REST_PATH, content, com.demomapas.model.rutaendpoint.model.Ruta.class);
    }

    @Override
    public UpdateRuta setAlt(java.lang.String alt) {
      return (UpdateRuta) super.setAlt(alt);
    }

    @Override
    public UpdateRuta setFields(java.lang.String fields) {
      return (UpdateRuta) super.setFields(fields);
    }

    @Override
    public UpdateRuta setKey(java.lang.String key) {
      return (UpdateRuta) super.setKey(key);
    }

    @Override
    public UpdateRuta setOauthToken(java.lang.String oauthToken) {
      return (UpdateRuta) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateRuta setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateRuta) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateRuta setQuotaUser(java.lang.String quotaUser) {
      return (UpdateRuta) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateRuta setUserIp(java.lang.String userIp) {
      return (UpdateRuta) super.setUserIp(userIp);
    }

    @Override
    public UpdateRuta set(String parameterName, Object value) {
      return (UpdateRuta) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Rutaendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Rutaendpoint}. */
    @Override
    public Rutaendpoint build() {
      return new Rutaendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link RutaendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setRutaendpointRequestInitializer(
        RutaendpointRequestInitializer rutaendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(rutaendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
