/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-03-08 at 06:16:10 UTC 
 * Modify at your own risk.
 */

package com.virtualef.pgj.service.personService;

/**
 * Service definition for PersonService (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link PersonServiceRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class PersonService extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the personService library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://civic-athlete-851.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "personService/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public PersonService(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  PersonService(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getPerson".
   *
   * This request holds the parameters needed by the personService server.  After setting any optional
   * parameters, call the {@link GetPerson#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetPerson getPerson(java.lang.Long id) throws java.io.IOException {
    GetPerson result = new GetPerson(id);
    initialize(result);
    return result;
  }

  public class GetPerson extends PersonServiceRequest<com.virtualef.pgj.service.personService.model.PersonDto> {

    private static final String REST_PATH = "persondto/{id}";

    /**
     * Create a request for the method "getPerson".
     *
     * This request holds the parameters needed by the the personService server.  After setting any
     * optional parameters, call the {@link GetPerson#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetPerson#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetPerson(java.lang.Long id) {
      super(PersonService.this, "GET", REST_PATH, null, com.virtualef.pgj.service.personService.model.PersonDto.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPerson setAlt(java.lang.String alt) {
      return (GetPerson) super.setAlt(alt);
    }

    @Override
    public GetPerson setFields(java.lang.String fields) {
      return (GetPerson) super.setFields(fields);
    }

    @Override
    public GetPerson setKey(java.lang.String key) {
      return (GetPerson) super.setKey(key);
    }

    @Override
    public GetPerson setOauthToken(java.lang.String oauthToken) {
      return (GetPerson) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPerson setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPerson) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPerson setQuotaUser(java.lang.String quotaUser) {
      return (GetPerson) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPerson setUserIp(java.lang.String userIp) {
      return (GetPerson) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetPerson setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetPerson set(String parameterName, Object value) {
      return (GetPerson) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getPersons".
   *
   * This request holds the parameters needed by the personService server.  After setting any optional
   * parameters, call the {@link GetPersons#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public GetPersons getPersons() throws java.io.IOException {
    GetPersons result = new GetPersons();
    initialize(result);
    return result;
  }

  public class GetPersons extends PersonServiceRequest<com.virtualef.pgj.service.personService.model.CollectionResponsePersonDto> {

    private static final String REST_PATH = "persondto";

    /**
     * Create a request for the method "getPersons".
     *
     * This request holds the parameters needed by the the personService server.  After setting any
     * optional parameters, call the {@link GetPersons#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetPersons#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected GetPersons() {
      super(PersonService.this, "GET", REST_PATH, null, com.virtualef.pgj.service.personService.model.CollectionResponsePersonDto.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPersons setAlt(java.lang.String alt) {
      return (GetPersons) super.setAlt(alt);
    }

    @Override
    public GetPersons setFields(java.lang.String fields) {
      return (GetPersons) super.setFields(fields);
    }

    @Override
    public GetPersons setKey(java.lang.String key) {
      return (GetPersons) super.setKey(key);
    }

    @Override
    public GetPersons setOauthToken(java.lang.String oauthToken) {
      return (GetPersons) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPersons setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPersons) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPersons setQuotaUser(java.lang.String quotaUser) {
      return (GetPersons) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPersons setUserIp(java.lang.String userIp) {
      return (GetPersons) super.setUserIp(userIp);
    }

    @Override
    public GetPersons set(String parameterName, Object value) {
      return (GetPersons) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertPerson".
   *
   * This request holds the parameters needed by the personService server.  After setting any optional
   * parameters, call the {@link InsertPerson#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.virtualef.pgj.service.personService.model.PersonDto}
   * @return the request
   */
  public InsertPerson insertPerson(com.virtualef.pgj.service.personService.model.PersonDto content) throws java.io.IOException {
    InsertPerson result = new InsertPerson(content);
    initialize(result);
    return result;
  }

  public class InsertPerson extends PersonServiceRequest<com.virtualef.pgj.service.personService.model.PersonDto> {

    private static final String REST_PATH = "persondto";

    /**
     * Create a request for the method "insertPerson".
     *
     * This request holds the parameters needed by the the personService server.  After setting any
     * optional parameters, call the {@link InsertPerson#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertPerson#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.virtualef.pgj.service.personService.model.PersonDto}
     * @since 1.13
     */
    protected InsertPerson(com.virtualef.pgj.service.personService.model.PersonDto content) {
      super(PersonService.this, "POST", REST_PATH, content, com.virtualef.pgj.service.personService.model.PersonDto.class);
    }

    @Override
    public InsertPerson setAlt(java.lang.String alt) {
      return (InsertPerson) super.setAlt(alt);
    }

    @Override
    public InsertPerson setFields(java.lang.String fields) {
      return (InsertPerson) super.setFields(fields);
    }

    @Override
    public InsertPerson setKey(java.lang.String key) {
      return (InsertPerson) super.setKey(key);
    }

    @Override
    public InsertPerson setOauthToken(java.lang.String oauthToken) {
      return (InsertPerson) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertPerson setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertPerson) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertPerson setQuotaUser(java.lang.String quotaUser) {
      return (InsertPerson) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertPerson setUserIp(java.lang.String userIp) {
      return (InsertPerson) super.setUserIp(userIp);
    }

    @Override
    public InsertPerson set(String parameterName, Object value) {
      return (InsertPerson) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removePerson".
   *
   * This request holds the parameters needed by the personService server.  After setting any optional
   * parameters, call the {@link RemovePerson#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemovePerson removePerson(java.lang.Long id) throws java.io.IOException {
    RemovePerson result = new RemovePerson(id);
    initialize(result);
    return result;
  }

  public class RemovePerson extends PersonServiceRequest<Void> {

    private static final String REST_PATH = "object/{id}";

    /**
     * Create a request for the method "removePerson".
     *
     * This request holds the parameters needed by the the personService server.  After setting any
     * optional parameters, call the {@link RemovePerson#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemovePerson#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemovePerson(java.lang.Long id) {
      super(PersonService.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemovePerson setAlt(java.lang.String alt) {
      return (RemovePerson) super.setAlt(alt);
    }

    @Override
    public RemovePerson setFields(java.lang.String fields) {
      return (RemovePerson) super.setFields(fields);
    }

    @Override
    public RemovePerson setKey(java.lang.String key) {
      return (RemovePerson) super.setKey(key);
    }

    @Override
    public RemovePerson setOauthToken(java.lang.String oauthToken) {
      return (RemovePerson) super.setOauthToken(oauthToken);
    }

    @Override
    public RemovePerson setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemovePerson) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemovePerson setQuotaUser(java.lang.String quotaUser) {
      return (RemovePerson) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemovePerson setUserIp(java.lang.String userIp) {
      return (RemovePerson) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemovePerson setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemovePerson set(String parameterName, Object value) {
      return (RemovePerson) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updatePerson".
   *
   * This request holds the parameters needed by the personService server.  After setting any optional
   * parameters, call the {@link UpdatePerson#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.virtualef.pgj.service.personService.model.PersonDto}
   * @return the request
   */
  public UpdatePerson updatePerson(com.virtualef.pgj.service.personService.model.PersonDto content) throws java.io.IOException {
    UpdatePerson result = new UpdatePerson(content);
    initialize(result);
    return result;
  }

  public class UpdatePerson extends PersonServiceRequest<com.virtualef.pgj.service.personService.model.PersonDto> {

    private static final String REST_PATH = "persondto";

    /**
     * Create a request for the method "updatePerson".
     *
     * This request holds the parameters needed by the the personService server.  After setting any
     * optional parameters, call the {@link UpdatePerson#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdatePerson#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.virtualef.pgj.service.personService.model.PersonDto}
     * @since 1.13
     */
    protected UpdatePerson(com.virtualef.pgj.service.personService.model.PersonDto content) {
      super(PersonService.this, "PUT", REST_PATH, content, com.virtualef.pgj.service.personService.model.PersonDto.class);
    }

    @Override
    public UpdatePerson setAlt(java.lang.String alt) {
      return (UpdatePerson) super.setAlt(alt);
    }

    @Override
    public UpdatePerson setFields(java.lang.String fields) {
      return (UpdatePerson) super.setFields(fields);
    }

    @Override
    public UpdatePerson setKey(java.lang.String key) {
      return (UpdatePerson) super.setKey(key);
    }

    @Override
    public UpdatePerson setOauthToken(java.lang.String oauthToken) {
      return (UpdatePerson) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdatePerson setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdatePerson) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdatePerson setQuotaUser(java.lang.String quotaUser) {
      return (UpdatePerson) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdatePerson setUserIp(java.lang.String userIp) {
      return (UpdatePerson) super.setUserIp(userIp);
    }

    @Override
    public UpdatePerson set(String parameterName, Object value) {
      return (UpdatePerson) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link PersonService}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link PersonService}. */
    @Override
    public PersonService build() {
      return new PersonService(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link PersonServiceRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setPersonServiceRequestInitializer(
        PersonServiceRequestInitializer personserviceRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(personserviceRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
