/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-03-31 at 04:55:50 UTC 
 * Modify at your own risk.
 */

package com.virtualef.pgj.dto.pruebaendpoint;

/**
 * Service definition for Pruebaendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link PruebaendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Pruebaendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the pruebaendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://civic-athlete-851.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "pruebaendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Pruebaendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Pruebaendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getPrueba".
   *
   * This request holds the parameters needed by the pruebaendpoint server.  After setting any
   * optional parameters, call the {@link GetPrueba#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetPrueba getPrueba(java.lang.Long id) throws java.io.IOException {
    GetPrueba result = new GetPrueba(id);
    initialize(result);
    return result;
  }

  public class GetPrueba extends PruebaendpointRequest<com.virtualef.pgj.dto.pruebaendpoint.model.Prueba> {

    private static final String REST_PATH = "prueba/{id}";

    /**
     * Create a request for the method "getPrueba".
     *
     * This request holds the parameters needed by the the pruebaendpoint server.  After setting any
     * optional parameters, call the {@link GetPrueba#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetPrueba#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetPrueba(java.lang.Long id) {
      super(Pruebaendpoint.this, "GET", REST_PATH, null, com.virtualef.pgj.dto.pruebaendpoint.model.Prueba.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPrueba setAlt(java.lang.String alt) {
      return (GetPrueba) super.setAlt(alt);
    }

    @Override
    public GetPrueba setFields(java.lang.String fields) {
      return (GetPrueba) super.setFields(fields);
    }

    @Override
    public GetPrueba setKey(java.lang.String key) {
      return (GetPrueba) super.setKey(key);
    }

    @Override
    public GetPrueba setOauthToken(java.lang.String oauthToken) {
      return (GetPrueba) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPrueba setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPrueba) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPrueba setQuotaUser(java.lang.String quotaUser) {
      return (GetPrueba) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPrueba setUserIp(java.lang.String userIp) {
      return (GetPrueba) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetPrueba setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetPrueba set(String parameterName, Object value) {
      return (GetPrueba) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertPrueba".
   *
   * This request holds the parameters needed by the pruebaendpoint server.  After setting any
   * optional parameters, call the {@link InsertPrueba#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.virtualef.pgj.dto.pruebaendpoint.model.Prueba}
   * @return the request
   */
  public InsertPrueba insertPrueba(com.virtualef.pgj.dto.pruebaendpoint.model.Prueba content) throws java.io.IOException {
    InsertPrueba result = new InsertPrueba(content);
    initialize(result);
    return result;
  }

  public class InsertPrueba extends PruebaendpointRequest<com.virtualef.pgj.dto.pruebaendpoint.model.Prueba> {

    private static final String REST_PATH = "prueba";

    /**
     * Create a request for the method "insertPrueba".
     *
     * This request holds the parameters needed by the the pruebaendpoint server.  After setting any
     * optional parameters, call the {@link InsertPrueba#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertPrueba#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.virtualef.pgj.dto.pruebaendpoint.model.Prueba}
     * @since 1.13
     */
    protected InsertPrueba(com.virtualef.pgj.dto.pruebaendpoint.model.Prueba content) {
      super(Pruebaendpoint.this, "POST", REST_PATH, content, com.virtualef.pgj.dto.pruebaendpoint.model.Prueba.class);
    }

    @Override
    public InsertPrueba setAlt(java.lang.String alt) {
      return (InsertPrueba) super.setAlt(alt);
    }

    @Override
    public InsertPrueba setFields(java.lang.String fields) {
      return (InsertPrueba) super.setFields(fields);
    }

    @Override
    public InsertPrueba setKey(java.lang.String key) {
      return (InsertPrueba) super.setKey(key);
    }

    @Override
    public InsertPrueba setOauthToken(java.lang.String oauthToken) {
      return (InsertPrueba) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertPrueba setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertPrueba) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertPrueba setQuotaUser(java.lang.String quotaUser) {
      return (InsertPrueba) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertPrueba setUserIp(java.lang.String userIp) {
      return (InsertPrueba) super.setUserIp(userIp);
    }

    @Override
    public InsertPrueba set(String parameterName, Object value) {
      return (InsertPrueba) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listPrueba".
   *
   * This request holds the parameters needed by the pruebaendpoint server.  After setting any
   * optional parameters, call the {@link ListPrueba#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListPrueba listPrueba() throws java.io.IOException {
    ListPrueba result = new ListPrueba();
    initialize(result);
    return result;
  }

  public class ListPrueba extends PruebaendpointRequest<com.virtualef.pgj.dto.pruebaendpoint.model.CollectionResponsePrueba> {

    private static final String REST_PATH = "prueba";

    /**
     * Create a request for the method "listPrueba".
     *
     * This request holds the parameters needed by the the pruebaendpoint server.  After setting any
     * optional parameters, call the {@link ListPrueba#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListPrueba#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListPrueba() {
      super(Pruebaendpoint.this, "GET", REST_PATH, null, com.virtualef.pgj.dto.pruebaendpoint.model.CollectionResponsePrueba.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListPrueba setAlt(java.lang.String alt) {
      return (ListPrueba) super.setAlt(alt);
    }

    @Override
    public ListPrueba setFields(java.lang.String fields) {
      return (ListPrueba) super.setFields(fields);
    }

    @Override
    public ListPrueba setKey(java.lang.String key) {
      return (ListPrueba) super.setKey(key);
    }

    @Override
    public ListPrueba setOauthToken(java.lang.String oauthToken) {
      return (ListPrueba) super.setOauthToken(oauthToken);
    }

    @Override
    public ListPrueba setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListPrueba) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListPrueba setQuotaUser(java.lang.String quotaUser) {
      return (ListPrueba) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListPrueba setUserIp(java.lang.String userIp) {
      return (ListPrueba) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListPrueba setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListPrueba setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListPrueba set(String parameterName, Object value) {
      return (ListPrueba) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removePrueba".
   *
   * This request holds the parameters needed by the pruebaendpoint server.  After setting any
   * optional parameters, call the {@link RemovePrueba#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemovePrueba removePrueba(java.lang.Long id) throws java.io.IOException {
    RemovePrueba result = new RemovePrueba(id);
    initialize(result);
    return result;
  }

  public class RemovePrueba extends PruebaendpointRequest<Void> {

    private static final String REST_PATH = "prueba/{id}";

    /**
     * Create a request for the method "removePrueba".
     *
     * This request holds the parameters needed by the the pruebaendpoint server.  After setting any
     * optional parameters, call the {@link RemovePrueba#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemovePrueba#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemovePrueba(java.lang.Long id) {
      super(Pruebaendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemovePrueba setAlt(java.lang.String alt) {
      return (RemovePrueba) super.setAlt(alt);
    }

    @Override
    public RemovePrueba setFields(java.lang.String fields) {
      return (RemovePrueba) super.setFields(fields);
    }

    @Override
    public RemovePrueba setKey(java.lang.String key) {
      return (RemovePrueba) super.setKey(key);
    }

    @Override
    public RemovePrueba setOauthToken(java.lang.String oauthToken) {
      return (RemovePrueba) super.setOauthToken(oauthToken);
    }

    @Override
    public RemovePrueba setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemovePrueba) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemovePrueba setQuotaUser(java.lang.String quotaUser) {
      return (RemovePrueba) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemovePrueba setUserIp(java.lang.String userIp) {
      return (RemovePrueba) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemovePrueba setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemovePrueba set(String parameterName, Object value) {
      return (RemovePrueba) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updatePrueba".
   *
   * This request holds the parameters needed by the pruebaendpoint server.  After setting any
   * optional parameters, call the {@link UpdatePrueba#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.virtualef.pgj.dto.pruebaendpoint.model.Prueba}
   * @return the request
   */
  public UpdatePrueba updatePrueba(com.virtualef.pgj.dto.pruebaendpoint.model.Prueba content) throws java.io.IOException {
    UpdatePrueba result = new UpdatePrueba(content);
    initialize(result);
    return result;
  }

  public class UpdatePrueba extends PruebaendpointRequest<com.virtualef.pgj.dto.pruebaendpoint.model.Prueba> {

    private static final String REST_PATH = "prueba";

    /**
     * Create a request for the method "updatePrueba".
     *
     * This request holds the parameters needed by the the pruebaendpoint server.  After setting any
     * optional parameters, call the {@link UpdatePrueba#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdatePrueba#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.virtualef.pgj.dto.pruebaendpoint.model.Prueba}
     * @since 1.13
     */
    protected UpdatePrueba(com.virtualef.pgj.dto.pruebaendpoint.model.Prueba content) {
      super(Pruebaendpoint.this, "PUT", REST_PATH, content, com.virtualef.pgj.dto.pruebaendpoint.model.Prueba.class);
    }

    @Override
    public UpdatePrueba setAlt(java.lang.String alt) {
      return (UpdatePrueba) super.setAlt(alt);
    }

    @Override
    public UpdatePrueba setFields(java.lang.String fields) {
      return (UpdatePrueba) super.setFields(fields);
    }

    @Override
    public UpdatePrueba setKey(java.lang.String key) {
      return (UpdatePrueba) super.setKey(key);
    }

    @Override
    public UpdatePrueba setOauthToken(java.lang.String oauthToken) {
      return (UpdatePrueba) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdatePrueba setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdatePrueba) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdatePrueba setQuotaUser(java.lang.String quotaUser) {
      return (UpdatePrueba) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdatePrueba setUserIp(java.lang.String userIp) {
      return (UpdatePrueba) super.setUserIp(userIp);
    }

    @Override
    public UpdatePrueba set(String parameterName, Object value) {
      return (UpdatePrueba) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Pruebaendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Pruebaendpoint}. */
    @Override
    public Pruebaendpoint build() {
      return new Pruebaendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link PruebaendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setPruebaendpointRequestInitializer(
        PruebaendpointRequestInitializer pruebaendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(pruebaendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
